/**
 * @file graphSlice.ts
 * @purpose Redux slice for managing graph window state in QoR Compare page
 * 
 * Manages floating, draggable graph windows with multiple chart types and series overlays.
 * Part of Phase 1: Infrastructure + Redux + FAB
 */

import { createSlice, type PayloadAction } from '@reduxjs/toolkit';
import type { RootState } from '@/store';

// ============================================
// CHART TYPES
// ============================================
export type ChartType = "line" | "scatter" | "bar" | "area" | "histogram";

// ============================================
// AXIS CONFIGURATION
// ============================================
export interface AxisConfig {
  type: "doeMetadata" | "metric";
  key: string;  // For doeMetadata: "label"|"PROJECT_NAME"|"BLOCK"|etc.
                // For metric: "Group!Label" format (e.g., "Power(mW)!combinational_Total")
}

// ============================================
// SOURCE OF TRUTH REFERENCES (for valid keys)
// ============================================
// DoE Metadata keys: Defined in `src/store/doeRegistry.ts` interface `DoEEntry`
//   Valid keys for xAxis/yAxis with type "doeMetadata": Any `keyof DoEEntry`
//   Common keys: "label", "PROJECT_NAME", "BLOCK", "NET_VER", "REVISION", "ECO_NUM", 
//                "POWER_SCENARIO", "TIMING_SCENARIO", "REVISION_MODE"
//   Array keys (not suitable for axes): "AVAILABLE_POWER_SCENARIOS", "AVAILABLE_SCENARIOS", "AVAILABLE_TIMING_SCENARIOS"
//   Reference: See DoEEntry type definition in doeRegistry.ts lines 25-52
//
// Metric keys: Defined in `src/variables/metricValueExtractor.ts` as `METRIC_EXTRACTORS` object keys
//   Format: "Group!Label" (e.g., "Power(mW)!combinational_Total", "Timing!setup(r2r)_WNS")
//   Reference: See METRIC_EXTRACTORS keys in metricValueExtractor.ts
//   Filtering for numeric-only metrics (deferred to Phase 3):
//     Use `getMetricFormatStrategy(key)` from helpers.ts - returns "number" | "skip-decimal" | "string-only"
//     Treat metrics as numeric UNLESS strategy is "string-only" (e.g., "Physical Info!ECO Runtime")

// ============================================
// RANGE CONFIGURATION
// ============================================
export interface RangeConfig {
  min: number | "auto";
  max: number | "auto";
}

// ============================================
// SERIES
// ============================================
export interface Series {
  id: string;           // Format: "s_0", "s_1", etc. (generated by reducer)
  metricKey: string;    // From METRIC_EXTRACTORS, "Group!Label" format
  color: string;        // Hex WITH # prefix (e.g., "#ff0000")
  enabled: boolean;     // Whether to render on chart
  chartType: ChartType;
}

export interface SeriesConfig {
  metricKey: string;
  color: string;
  enabled: boolean;
  chartType?: ChartType;
}

// ============================================
// GRAPH WINDOW
// ============================================
export interface GraphWindow {
  // REQUIRED - always present after creation
  id: string;              // Format: "gw_0", "gw_1", etc. (generated by reducer)
  chartType: ChartType;
  xAxis: AxisConfig;
  yAxis: AxisConfig;
  series: Series[];        // Max 10 per window
  xRange: RangeConfig;
  yRange: RangeConfig;
  
  // OPTIONAL - set later by component or actions
  position?: { x: number; y: number };   // Set by component on drag end
  size?: { width: number; height: number }; // Set by component on resize end
  isMinimized?: boolean;   // Default: false, toggled by toggleMinimize
  zIndex?: number;         // For stacking order, set by bringToFront
}

// ============================================
// GRAPH WINDOW CONFIG (for URL restore / bulk set)
// ============================================
export interface GraphWindowConfig {
  chartType: ChartType;
  xAxis: AxisConfig;
  yAxis: AxisConfig;
  series: SeriesConfig[]; // NO id
  xRange: RangeConfig;
  yRange: RangeConfig;
  // NOTE: NO id, position, size, isMinimized, zIndex - assigned by reducer/component
}

// ============================================
// REDUX STATE
// ============================================
export interface GraphState {
  windows: GraphWindow[];
  nextWindowId: number;                          // Counter for window IDs
  nextSeriesIdByWindow: Record<string, number>;  // Per-window series ID counters
  maxZIndex: number;                             // Counter for z-index assignment
}

// Initial state
const initialState: GraphState = {
  windows: [],
  nextWindowId: 0,
  nextSeriesIdByWindow: {},
  maxZIndex: 0,
};

// ============================================
// SLICE
// ============================================
const graphSlice = createSlice({
  name: 'graph',
  initialState,
  reducers: {
    // ============================================
    // addGraphWindow
    // ============================================
    addGraphWindow: (state, action: PayloadAction<Partial<GraphWindowConfig> | undefined>) => {
      // Guard: Max 10 windows
      if (state.windows.length >= 10) {
        return; // No-op, silently ignore
      }
      
      // Generate window ID
      const id = `gw_${state.nextWindowId}`;
      state.nextWindowId++;
      
      // Merge with defaults
      const config = action.payload ?? {};
      const DEFAULT_CONFIG: GraphWindowConfig = {
        chartType: "line",
        xAxis: { type: "doeMetadata", key: "label" },
        yAxis: { type: "metric", key: "Power(mW)!combinational_Total" },
        // DEFAULT SERIES: Include one series matching yAxis so charts show data immediately
        // This ensures Phase 2 can render actual charts without user configuration
        series: [
          { metricKey: "Power(mW)!combinational_Total", color: "#2563eb", enabled: true, chartType: "line" }
        ],
        xRange: { min: "auto", max: "auto" },
        yRange: { min: "auto", max: "auto" },
      };
      
      // GUARD: Enforce max 10 series per window (truncate if payload exceeds)
      const inputSeries = config.series ?? DEFAULT_CONFIG.series;
      const truncatedSeries = inputSeries.slice(0, 10);
      
      // Create series with IDs
      const seriesWithIds: Series[] = truncatedSeries.map((s, i) => ({
        ...s,
        id: `s_${i}`,
        color: s.color.startsWith('#') ? s.color : `#${s.color}`,
        chartType: s.chartType ?? "line",
      }));
      
      // Assign zIndex
      state.maxZIndex++;
      
      // Create window
      const newWindow: GraphWindow = {
        id,
        chartType: config.chartType ?? DEFAULT_CONFIG.chartType,
        xAxis: config.xAxis ?? DEFAULT_CONFIG.xAxis,
        yAxis: config.yAxis ?? DEFAULT_CONFIG.yAxis,
        series: seriesWithIds,
        xRange: config.xRange ?? DEFAULT_CONFIG.xRange,
        yRange: config.yRange ?? DEFAULT_CONFIG.yRange,
        zIndex: state.maxZIndex,
        // position, size, isMinimized are undefined initially
      };
      
      state.windows.push(newWindow);
      state.nextSeriesIdByWindow[id] = seriesWithIds.length;
    },

    // ============================================
    // removeGraphWindow
    // ============================================
    removeGraphWindow: (state, action: PayloadAction<string>) => {
      const id = action.payload;
      state.windows = state.windows.filter(w => w.id !== id);
      delete state.nextSeriesIdByWindow[id];
      // Note: nextWindowId and maxZIndex are NOT decremented (IDs never reuse)
    },

    // ============================================
    // updateGraphWindow
    // ============================================
    updateGraphWindow: (state, action: PayloadAction<{ id: string; changes: Partial<Omit<GraphWindow, 'id' | 'series'>> }>) => {
      const { id, changes } = action.payload;
      const window = state.windows.find(w => w.id === id);
      if (window) {
        Object.assign(window, changes);
      }
    },

    // ============================================
    // addSeriesToWindow
    // ============================================
    addSeriesToWindow: (state, action: PayloadAction<{ windowId: string; series: SeriesConfig }>) => {
      const { windowId, series } = action.payload;
      const window = state.windows.find(w => w.id === windowId);
      
      // Guard: Max 10 series
      if (!window || window.series.length >= 10) {
        return; // No-op
      }
      
      // Generate series ID
      const nextId = state.nextSeriesIdByWindow[windowId] ?? 0;
      const newSeries: Series = {
        ...series,
        id: `s_${nextId}`,
        color: series.color.startsWith('#') ? series.color : `#${series.color}`,
        chartType: series.chartType ?? "line",
      };
      
      window.series.push(newSeries);
      state.nextSeriesIdByWindow[windowId] = nextId + 1;
    },

    // ============================================
    // removeSeriesFromWindow
    // ============================================
    removeSeriesFromWindow: (state, action: PayloadAction<{ windowId: string; seriesId: string }>) => {
      const { windowId, seriesId } = action.payload;
      const window = state.windows.find(w => w.id === windowId);
      if (window) {
        window.series = window.series.filter(s => s.id !== seriesId);
        // Note: nextSeriesIdByWindow is NOT decremented (IDs never reuse)
      }
    },

    // ============================================
    // toggleSeriesEnabled
    // ============================================
    toggleSeriesEnabled: (state, action: PayloadAction<{ windowId: string; seriesId: string }>) => {
      const { windowId, seriesId } = action.payload;
      const window = state.windows.find(w => w.id === windowId);
      const series = window?.series.find(s => s.id === seriesId);
      if (series) {
        series.enabled = !series.enabled;
      }
    },

    updateSeriesChartType: (state, action: PayloadAction<{ windowId: string; seriesId: string; chartType: ChartType }>) => {
      const { windowId, seriesId, chartType } = action.payload;
      const window = state.windows.find(w => w.id === windowId);
      const series = window?.series.find(s => s.id === seriesId);
      if (series) {
        series.chartType = chartType;
      }
    },

    // ============================================
    // setWindowPosition
    // ============================================
    setWindowPosition: (state, action: PayloadAction<{ id: string; position: { x: number; y: number } }>) => {
      const { id, position } = action.payload;
      const window = state.windows.find(w => w.id === id);
      if (window) {
        window.position = position;
      }
    },

    // ============================================
    // setWindowSize
    // ============================================
    setWindowSize: (state, action: PayloadAction<{ id: string; size: { width: number; height: number } }>) => {
      const { id, size } = action.payload;
      const window = state.windows.find(w => w.id === id);
      if (window) {
        window.size = size;
      }
    },

    // ============================================
    // toggleMinimize
    // ============================================
    toggleMinimize: (state, action: PayloadAction<string>) => {
      const window = state.windows.find(w => w.id === action.payload);
      if (window) {
        window.isMinimized = !window.isMinimized;
      }
    },

    // ============================================
    // bringToFront
    // ============================================
    bringToFront: (state, action: PayloadAction<string>) => {
      const window = state.windows.find(w => w.id === action.payload);
      if (window) {
        state.maxZIndex++;
        window.zIndex = state.maxZIndex;
      }
    },

    // ============================================
    // cloneWindow
    // ============================================
    cloneWindow: (state, action: PayloadAction<string>) => {
      const sourceId = action.payload;
      const source = state.windows.find(w => w.id === sourceId);
      
      // Guard: Max 10 windows
      if (!source || state.windows.length >= 10) {
        return; // No-op
      }
      
      // Generate new window ID
      const newId = `gw_${state.nextWindowId}`;
      state.nextWindowId++;
      
      // Clone series with NEW IDs
      const clonedSeries: Series[] = source.series.map((s, i) => ({
        ...s,
        id: `s_${i}`,
      }));
      
      // Assign zIndex
      state.maxZIndex++;
      
      // Create cloned window (position/size/isMinimized are reset)
      const clonedWindow: GraphWindow = {
        ...source,
        id: newId,
        series: clonedSeries,
        position: undefined,    // Component will compute
        size: undefined,        // Component will use default
        isMinimized: false,     // Cloned window starts expanded
        zIndex: state.maxZIndex,
      };
      
      state.windows.push(clonedWindow);
      state.nextSeriesIdByWindow[newId] = clonedSeries.length;
    },

    // ============================================
    // setGraphWindows (for URL restore)
    // ============================================
    setGraphWindows: (state, action: PayloadAction<GraphWindowConfig[]>) => {
      // REPLACES entire windows array (for URL restore)
      let configs = action.payload;
      
      // GUARD: Enforce max 10 windows (truncate if exceeds)
      if (configs.length > 10) {
        configs = configs.slice(0, 10);
        // Note: Truncation is logged by caller (useURLSync), not here
      }
      
      // Reset state
      state.windows = [];
      state.nextSeriesIdByWindow = {};
      // Keep nextWindowId incrementing (never reset to avoid ID collision in session)
      
      configs.forEach((config) => {
        const windowId = `gw_${state.nextWindowId}`;
        state.nextWindowId++;
        state.maxZIndex++;
        
        // GUARD: Enforce max 10 series per window (truncate if exceeds)
        const truncatedSeries = config.series.slice(0, 10);
        
        const seriesWithIds: Series[] = truncatedSeries.map((s, i) => ({
          ...s,
          id: `s_${i}`,
          color: s.color.startsWith('#') ? s.color : `#${s.color}`,
          chartType: s.chartType ?? "line",
        }));
        
        const window: GraphWindow = {
          id: windowId,
          chartType: config.chartType,
          xAxis: config.xAxis,
          yAxis: config.yAxis,
          series: seriesWithIds,
          xRange: config.xRange,
          yRange: config.yRange,
          zIndex: state.maxZIndex,
          // position, size, isMinimized are undefined
        };
        
        state.windows.push(window);
        state.nextSeriesIdByWindow[windowId] = seriesWithIds.length;
      });
    },
  },
});

// ============================================
// SELECTORS
// ============================================
export const selectAllGraphWindows = (state: RootState) => state.graph.windows;
export const selectGraphWindowById = (id: string) => 
  (state: RootState) => state.graph.windows.find(w => w.id === id);
export const selectGraphWindowCount = (state: RootState) => state.graph.windows.length;

// ============================================
// EXPORTS
// ============================================
export const {
  addGraphWindow,
  removeGraphWindow,
  updateGraphWindow,
  addSeriesToWindow,
  removeSeriesFromWindow,
  toggleSeriesEnabled,
  updateSeriesChartType,
  setWindowPosition,
  setWindowSize,
  toggleMinimize,
  bringToFront,
  cloneWindow,
  setGraphWindows,
} = graphSlice.actions;

export default graphSlice.reducer;
